spring.application.name=secure-vault
spring.datasource.url=jdbc:postgresql://localhost:5432/securevault_db
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

#spring.jpa.hibernate.ddl-auto=create
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
server.port=8081

# JWT Ayarlari
# (Burasi disaridan yonetilebilir hale geldi)
application.security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
application.security.jwt.expiration=86400000
# MINIO SETTINGS
minio.endpoint=http://localhost:9000
minio.accessKey=minioadmin
minio.secretKey=minioadmin
minio.bucketName=secure-vault-bucket
# RABBITMQ AYARLARI
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
# REDIS AYARLARI
spring.data.redis.host=localhost
spring.data.redis.port=6379

# SPRING CACHE (Onbellek) AYARLARI
spring.cache.type=redis